language: java
jdk: openjdk8

branches:
  only:
    - master

services:
  - docker

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script: 
  #- ./gradlew clean build
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} 
  - ./gradlew dockerPush song7749/db-client:latest
  - ./gradlew dockerPush song7749/incident:latest
  - ./gradlew dockerPush song7749/srcenter:latest  