language: java
jdk: openjdk8

branches:
  only:
    - master

services:
  - docker

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
  #- ./gradlew clean build
  # docker build
  - docker build -t db-client:latest --build-arg JAR_FILE=song7749-module-dbclient/build/libs/song7749-module-dbclient.jar ./
  - docker build -t incident:latest  --build-arg JAR_FILE=song7749-module-incident/build/libs/song7749-module-incident.jar ./
  - docker build -t srcenter:latest  --build-arg JAR_FILE=song7749-module-srcenter/build/libs/song7749-module-srcenter.jar ./
  # docker login
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} 
  # docker tag
  - docker tag db-client:latest song7749/db-client:latest
  - docker tag incident:latest  song7749/incident:latest
  - docker tag srcenter:latest  song7749/srcenter:latest  
  # docker push
  - docker push song7749/db-client:latest
  - docker push song7749/incident:latest
  - docker push song7749/srcenter:latest  