language: java
jdk: openjdk8

branches:
  only:
    - master

services:
  - docker

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: 
  #- ./gradlew clean build
  # docker login
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} 
  # docker push
  - ./gradlew "song7749-module-dbclient:dockerPush"
  - ./gradlew "song7749-module-incident:dockerPush"
  - ./gradlew "song7749-module-srcenter:dockerPush"  