##############################################################################
# 공통 실행 환경 
##############################################################################
# server define
server:
  port: 9009

# spring config 
spring:
  # profile active
  profiles:
    active:
    - local
  # banner
  banner:
    charset: utf-8
    location: classpath:config/banner.txt
  main:
    allow-bean-definition-overriding: true
  # 스프링 영속성을 Controller 까지 확대. http://kingbbode.tistory.com/27 참고 바람
  # JPA Time Zone 설정을 추가함 (JPA 의 시간은 계속 GMT 0 이다...) -- 별짓을 다 해봐도 변화가 없네...
  jpa: 
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
##############################################################################
# local 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: local
  profiles.include:
  # 추가 환경 구성을 include 한다. 
    - database-h2-mem-mysql
  # 기초 데이터 로딩
  datasource:
   data:
    - classpath:./initDatabase.sql
  # jpa 추가 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate : 
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    remote:
      restart:
        enabled: false        

        
##############################################################################
# dev 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: dev
  profiles.include:
  # 추가 환경 구성을 include 한다. 
    - database-mysql-prd
  # jpa 추가 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate : 
        format_sql: true
        use_sql_comments: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    remote:
      restart:
        enabled: false        
        
        
##############################################################################
# stage 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: stage
  profiles.include:
  # 추가 환경 구성을 include 한다. 
    - database-h2-file-mysql
  # jpa 추가 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate : 
        format_sql: false
        use_sql_comments: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    remote:
      restart:
        enabled: false        
        
##############################################################################
# production 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: production
  profiles.include:
  # 추가 환경 구성을 include 한다. 
    - database-h2-file-mysql
  # jpa 추가 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate : 
        format_sql: false
        use_sql_comments: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    remote:
      restart:
        enabled: false
        
##############################################################################
# Database 환경 설정 
##############################################################################
---
spring:
  # profile 설정
  profiles: database-h2-mem-mysql
  # datasource    
  datasource:
    url:  jdbc:h2:mem:dbclient;Mode=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1  
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    databaseName: DB Client Local Database
    schemaName: PUBLIC
    host: jdbc:h2:mem:~/dbclient
    port: 


---
spring:
  # profile 설정
  profiles: database-h2-file-mysql
  # datasource    
  datasource:
    url:  jdbc:h2:file:~/dbclient;Mode=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1  
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    databaseName: DB Client Local Database
    schemaName: PUBLIC
    host: jdbc:h2:file:~/dbclient
    port: 
  
---
spring:
  # profile 설정
  profiles: database-mariadb-dev
   # datasource    
  datasource:
    url: jdbc:mariadb://local-dev:4306/dbclient?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Seoul  
    username: dbclient
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
    databaseName: DB Client Local Database
    schemaName: dbClient
    host: local-dev
    port: 4306

---
spring:
  # profile 설정
  profiles: database-mysql-prd
   # datasource    
  datasource:
    url: jdbc:mysql://local-dev:3306/dbclient?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: dbclient
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    databaseName: DB Client Local Database
    schemaName: dbclient
    host: local-dev
    port: 39212    