##############################################################################
# 공통 실행 환경 
##############################################################################
# server define
server:
  port: 9009

# spring config 
spring:
  # profile active
  profiles:
    active:
    - local
#   - mariadb
  # banner
  banner:
    charset: utf-8
    location: classpath:config/srcenter-banner.txt
  # Boot 2.1 부터 프로젝트 상속 관계인 경우 bean 이 2중 생성되는 문제로 overwrite 옵션을 켜야 한다. 
  main:
    allow-bean-definition-overriding: true

##############################################################################
# local 추가 환경 
##############################################################################

---
---
spring:
  # profile 설정
  profiles: local

##############################################################################
# dev 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: dev
        
        
##############################################################################
# stage 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: stage
        
##############################################################################
# production 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: production
        
##############################################################################
# mariadb 추가 환경 
##############################################################################

---
spring:
  # profile 설정
  profiles: mariadb