##############################################################################
# MVC 공통 실행 환경 
##############################################################################
# server define
server:
  tomcat:
    uri-encoding: UTF-8

  # mvc
  mvc:
    favicon:
      enabled: false
    # mvc 404 exception throw 
    throw-exception-if-no-handler-found: true

  # resource
  resources:
    # static contents handler use
    add-mappings: false

  # http encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # file upload
  servlet:
    multipart: 
      max-file-size: 50MB
      max-request-size: 50MB   

spring:
  mvc:
    formcontent:
      filter:
        enabled: true